language:
  - c
install:
  - sudo apt-get update
  - sudo apt-get install linuxdoc-tools linuxdoc-tools-info binutils-mingw-w64-i686 gcc-mingw-w64-i686 sshpass cmake python3 python3-pip
  - sudo pip3 install --upgrade pip setuptools wheel
  - sudo pip3 install --only-binary=numpy,scipy numpy scipy
  - sudo pip3 install pytest-cov
  - sudo pip3 install coveralls
  - sudo CC=g++-7 pip3 install revkit
  - sudo pip3 install dormouse
script:
  - mkdir _build && cd _build && cmake -DUSE_OPENCL=OFF -DENABLE_COMPLEX8=OFF .. && make -j 8 all
  - cd .. && rm -r _build
  - mkdir _build && cd _build && cmake -DUSE_OPENCL=OFF -DENABLE_COMPLEX8=ON .. && make -j 8 all
  - ./unittest --proc-cpu
  - cd .. && git clone https://github.com/vm6502q/ProjectQ.git && cd ProjectQ
  - pip3 install -e . --global-option="--with-qracksimulator"
  - cd build && export OMP_NUM_THREADS=1 && pytest projectq --cov projectq
