find_package(Boost)
if (Boost_FOUND OR Boost_INCLUDE_DIR)
    include_directories(${Boost_INCLUDE_DIR})
    target_compile_definitions (qrack PUBLIC BOOST_AVAILABLE=1)
endif (Boost_FOUND OR Boost_INCLUDE_DIR)
